name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: macos-14
          - os: windows-2022
            comp: msvc2022
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Checkout qttools
        uses: actions/checkout@v4
        with:
          repository: qt/qttools
          ref: 6.10.0
          path: qttools

      - name: Checkout static Qt release
        id: qtsetup
        uses: k61n/qt_static_builds/.github/actions/checkout@main
        with:
          version: "6.10.0"
          compiler: ${{matrix.comp}}

      - name: Build qttools
        shell: bash
        if: runner.os != 'Windows'
        run: |
          ls -l
          ls -l ${{steps.qtsetup.outputs.qtpath}}
          ls qttools
      - name: Build qttools
        shell: powershell
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem -Force
          Get-ChildItem -Force "${{ steps.qtsetup.outputs.qtpath }}"
          Get-ChildItem -Force "qttools"
