name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: macos-14
          - os: windows-2022
            comp: llvm1706
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Checkout qttools
        uses: actions/checkout@v4
        with:
          repository: qt/qttools
          ref: 6.10.0
          path: qttools
          submodules: recursive

      - name: Checkout static Qt release
        id: qtsetup
        uses: k61n/qt_static_builds/.github/actions/checkout@main
        with:
          version: "6.10.0"
          compiler: ${{matrix.comp}}

      - name: Build qttools
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cores=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
          mkdir -p qttools/build && cd qttools/build
          cmake \
            .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=${{steps.qtsetup.outputs.qtpath}}
          cmake --build . --target designer --parallel ${cores}
          ls -l bin
      - name: Setup llvm
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $arch = $env:PROCESSOR_ARCHITECTURE.ToLower() -replace '^arm64$', 'aarch64' -replace '^amd64$', 'i686'
          Start-BitsTransfer -Source `
            "https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-ucrt-${arch}.zip" `
            -Destination .
          7z x .\llvm-mingw-20231128-ucrt-${arch}.zip -o"./"
          Rename-Item -Path "llvm-mingw-20231128-ucrt-${arch}" -NewName "llvm"
          Remove-Item "llvm-mingw-20231128-ucrt-${arch}.zip"
          choco install ninja -f -y
      - name: Build qttools
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $llvm_path = (Resolve-Path "llvm").Path
          $env:Path = "${llvm_path}\bin;" + $env:Path
          mkdir qttools/build
          cd qttools/build
          cmake `
            .. `
            -GNinja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_PREFIX_PATH=${{steps.qtsetup.outputs.qtpath}} `
            -DCMAKE_EXE_LINKER_FLAGS="-static" `
            -DCMAKE_SHARED_LINKER_FLAGS="-static"
          cmake --build . --target designer --parallel ${env:NUMBER_OF_PROCESSORS}
          Get-ChildItem -Force "bin"
#      - uses: actions/upload-artifact@v4
#        with:
#          name: ${{steps.build.outputs.fn}}
#          path: qttools/bin
