name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: macos-15
          - os: macos-15-intel
          - os: windows-2022
            comp: msvc2022
          - os: windows-11-arm
            comp: msvc2022
    steps:

      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Checkout qttools
        uses: ./.github/actions/checkout_qttools
        with:
          version: 6.11.1

      - name: Checkout static Qt release
        id: qtsetup
        uses: k61n/qt_static_builds/.github/actions/checkout@main
        with:
          version: 6.11.1
          compiler: ${{matrix.comp}}

      - name: Build qttools
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cores=$(nproc 2>/dev/null || sysctl -n hw.ncpu)
          if [[ "$(echo ${RUNNER_OS} | tr '[:upper:]' '[:lower:]')" == "linux" ]]; then
            sed -i 's/\${optional_components}/Gui/g' qttools/CMakeLists.txt
          fi
          mkdir -p qttools/build && cd qttools/build
          cmake \
            .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=${{steps.qtsetup.outputs.qtpath}}
          cmake --build . --target designer --parallel ${cores}
          os=$(echo $RUNNER_OS | tr '[:upper:]' '[:lower:]')
          arch=$(uname -m)
          cd bin
          ditto -c -k --sequesterRsrc --keepParent "Designer.app" designer-${os}-${arch}.zip
          echo "name=designer-${os}-${arch}.zip" >> $GITHUB_ENV
          echo "path=$(realpath designer-${os}-${arch}.zip)" >> $GITHUB_ENV

      - name: env
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $os = $env:RUNNER_OS.ToLower()
          $arch = $env:PROCESSOR_ARCHITECTURE.ToLower()
          $vspath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
          Add-Content -Path $env:GITHUB_ENV -Value "os=${os}"
          Add-Content -Path $env:GITHUB_ENV -Value ("arch=" + ($arch -replace '^amd64$', 'x64'))
          Add-Content -Path $env:GITHUB_ENV -Value "vspath=${vspath}"
          mkdir qttools/build

      - name: Build qttools
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call "${{env.vspath}}\VC\Auxiliary\Build\vcvarsall.bat" ${{env.arch}}
          cd qttools/build
          cmake ^
            .. ^
            -GNinja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_PREFIX_PATH=${{steps.qtsetup.outputs.qtpath}} ^
            -DCMAKE_EXE_LINKER_FLAGS="-static" ^
            -DCMAKE_SHARED_LINKER_FLAGS="-static"
          cmake --build . --target designer --config Release

      - name: Prepare artifacts
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cd qttools/build
          $path = (Resolve-Path "bin/designer.exe").Path
          Add-Content -Path $env:GITHUB_ENV -Value "name=designer-${{env.os}}-${{env.arch}}.zip"
          Add-Content -Path $env:GITHUB_ENV -Value "path=${path}"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.name}}
          path: ${{env.path}}
